// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return windows;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpWDt0T-hkyFpqLdC9XJUxO30GBw-ECvw',
    appId: '1:1071926374066:android:2f26ed1431daea4bab23ab',
    messagingSenderId: '1071926374066',
    projectId: 'kernel-panic-app',
    storageBucket: 'kernel-panic-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkw5MlxElWTJxhMsDNspyeaA5P5LKBxZo',
    appId: '1:1071926374066:ios:389c9f9798aabc22ab23ab',
    messagingSenderId: '1071926374066',
    projectId: 'kernel-panic-app',
    storageBucket: 'kernel-panic-app.firebasestorage.app',
    iosBundleId: 'com.example.kernelpanic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1S2d2zK_ko692jx30zliU4THW2Nq1-8g',
    appId: '1:1071926374066:web:a1617959fd2b3cebab23ab',
    messagingSenderId: '1071926374066',
    projectId: 'kernel-panic-app',
    authDomain: 'kernel-panic-app.firebaseapp.com',
    storageBucket: 'kernel-panic-app.firebasestorage.app',
  );
}
